//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.asp
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class ACHIEVEMENT
    {
        [DataMember(Order = 1)]
        public int AchievementID { get; set; }
        [DataMember(Order = 2)]
        public byte[] Title { get; set; }
        [DataMember(Order = 3)]
        public string Type { get; set; }
        [DataMember(Order = 4)]
        public string Rank { get; set; }
        [DataMember(Order = 5)]
        public string Condition { get; set; }
    }
}
