//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDEE
    {
        public int AttendeeID { get; set; }
        public string Status { get; set; }
        public int EventID { get; set; }
        public int UserID { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual USER USER { get; set; }
    }
}
