//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public EVENT()
        {
            this.ATTENDEEs = new HashSet<ATTENDEE>();
            this.GALLERies = new HashSet<GALLERY>();
        }
    
        public int EventID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Duration { get; set; }
        public string CreatedDate { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Status { get; set; }
        public string Privacy { get; set; }
        public Nullable<int> PinID { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<ATTENDEE> ATTENDEEs { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<GALLERY> GALLERies { get; set; }
        public virtual PIN PIN { get; set; }
    }
}
