//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.asp
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class FRIEND_LIST
    {
        [DataMember(Order = 1)]
        public int Firend_ListID { get; set; }
        [DataMember(Order = 2)]
        public int UserID { get; set; }
        [DataMember(Order = 3)]
        public int FriendID { get; set; }

        [DataMember(Order = 4)]
        public virtual USER USER { get; set; }
    }
}
