//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALLERY
    {
        public GALLERY()
        {
            this.IMAGEs = new HashSet<IMAGE>();
        }
    
        public int GalleryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PetID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EventID { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual USER USER { get; set; }
        public virtual PET PET { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual ICollection<IMAGE> IMAGEs { get; set; }
    }
}
