//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE
    {
        public int ImageID { get; set; }
        public string Type { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PetID { get; set; }
        public Nullable<int> GalleryID { get; set; }
    
        public virtual GALLERY GALLERY { get; set; }
        public virtual PIN PIN { get; set; }
    }
}
