//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION
    {
        public ORGANIZATION()
        {
            this.ADVERTs = new HashSet<ADVERT>();
        }
    
        public int OrganizationID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<ADVERT> ADVERTs { get; set; }
    }
}
