//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIN
    {
        public int PinID { get; set; }
        public int ImageID { get; set; }
        public string Type { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual IMAGE IMAGE { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual PET PET { get; set; }
        public virtual USER USER { get; set; }
    }
}
