//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW
    {
        public int ReviewID { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string Likes { get; set; }
        public string Dislikes { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StrayID { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
        public virtual USER USER { get; set; }
        public virtual STRAY STRAY { get; set; }
    }
}
